#FROM maven:3.8.2-openjdk-17 AS build
FROM maven:3.8.5-openjdk-17-slim AS build
WORKDIR /app
COPY pom.xml ./
COPY src ./src
RUN mvn clean package -DskipTests


#FROM openjdk:18-alpine AS run
FROM eclipse-temurin:21-jre-alpine AS run
WORKDIR /run

ARG USER=devops
ENV HOME=/home/$USER

COPY --from=build /app/target/demo-0.0.1-SNAPSHOT.jar /run/demo.jar

RUN adduser -D $USER && chown $USER:$USER /run/demo.jar
USER $USER
EXPOSE 8080
#CMD java -jar /run/demo.jar
CMD ["java", "-jar", "/run/demo.jar"]